# Generated by Django 3.1.6 on 2021-02-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_age', models.IntegerField()),
                ('user_dob', models.DateField()),
                ('user_id', models.IntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_country', models.CharField(max_length=100)),
            ],
        ),
    ]
